"""A pure-Python reader and writer for TES3 plugin files.

**Why this exists.** The toolkit's authoritative plugin reader is ``tes3conv``,
a console program it shells out to. That works, but it is a subprocess and a
binary to locate and bundle, it spawns a window on Windows, and it refuses a
whole file on one record it does not know (OpenMW's ``LUAL``, for one, which is
why :mod:`wraithguard.land.native` exists). A library that reads and writes the
format *in process* removes the subprocess, and -- record by record -- lets the
tool understand plugins itself, now and in the future.

**What it is.** A faithful port of the `tes3` Rust crate's ``esp`` library
(``libs/esp`` in the checkout beside this repo). The wire format is the crate's,
verified against it: little-endian primitives, four-byte tags, length-prefixed
Windows-1252 strings, and the record/subrecord framing
:mod:`wraithguard.esp.io` documents. Each record type is a small class that
mirrors one ``types/*.rs`` file -- its fields, and the exact tag-dispatch its
``Load``/``Save`` perform -- so a value read and written back is byte-for-byte
what it was.

**Shape.** :func:`read_plugin` turns bytes into a list of record objects;
:func:`write_plugin` turns them back. :mod:`wraithguard.esp.io` is the binary
layer everything is built on; :mod:`wraithguard.esp.enums` and
:mod:`wraithguard.esp.flags` are the crate's enum and bitflags tables, generated
from its source so a variant is spelled and valued exactly as the engine reads
it. Records are ported incrementally; a tag with no class yet is preserved
verbatim rather than lost, so the reader is always safe to run.
"""

from __future__ import annotations

from wraithguard.esp.io import EspError, Reader, Writer
from wraithguard.esp.json import (
    EspJsonError,
    plugin_from_json,
    plugin_to_json,
    record_from_json,
    record_to_json,
)
from wraithguard.esp.masters import (
    RemoveMasterReport,
    RenameMasterReport,
    remove_master,
    remove_master_from_bytes,
    rename_master,
    rename_master_in_bytes,
)
from wraithguard.esp.plugin import read_header, read_plugin, write_plugin
from wraithguard.esp.record import Record, UnknownRecord
from wraithguard.esp.records import (
    Activator,
    Alchemy,
    AlchemyData,
    Apparatus,
    ApparatusData,
    Armor,
    ArmorData,
    AtmosphereData,
    BipedObject,
    Birthsign,
    Bodypart,
    BodypartData,
    Book,
    BookData,
    Cell,
    CellData,
    Class,
    ClassData,
    Clothing,
    ClothingData,
    Container,
    Creature,
    CreatureData,
    Dialogue,
    DialogueData,
    DialogueInfo,
    Door,
    Effect,
    Enchanting,
    EnchantingData,
    Faction,
    FactionData,
    FactionReaction,
    FactionRequirement,
    Filter,
    GameSetting,
    GlobalVariable,
    Header,
    Ingredient,
    IngredientData,
    Landscape,
    LandscapeTexture,
    LeveledCreature,
    LeveledItem,
    Light,
    LightData,
    Lockpick,
    LockpickData,
    MagicEffect,
    MagicEffectData,
    MiscItem,
    MiscItemData,
    Npc,
    NpcData,
    NpcStats,
    PathGrid,
    PathGridData,
    PathGridPoint,
    Probe,
    ProbeData,
    Race,
    RaceData,
    Reference,
    Region,
    RepairItem,
    RepairItemData,
    Script,
    ScriptHeader,
    Skill,
    SkillData,
    Sound,
    SoundData,
    SoundGen,
    Spell,
    SpellData,
    StartScript,
    Static,
    Weapon,
    WeaponData,
    WeatherChances,
)

__all__ = [
    "Activator",
    "Alchemy",
    "AlchemyData",
    "Apparatus",
    "ApparatusData",
    "Armor",
    "ArmorData",
    "AtmosphereData",
    "BipedObject",
    "Birthsign",
    "Bodypart",
    "BodypartData",
    "Book",
    "BookData",
    "Cell",
    "CellData",
    "Class",
    "ClassData",
    "Clothing",
    "ClothingData",
    "Container",
    "Creature",
    "CreatureData",
    "Dialogue",
    "DialogueData",
    "DialogueInfo",
    "Door",
    "Effect",
    "Enchanting",
    "EnchantingData",
    "EspError",
    "EspJsonError",
    "Faction",
    "FactionData",
    "FactionReaction",
    "FactionRequirement",
    "Filter",
    "GameSetting",
    "GlobalVariable",
    "Header",
    "Ingredient",
    "IngredientData",
    "Landscape",
    "LandscapeTexture",
    "LeveledCreature",
    "LeveledItem",
    "Light",
    "LightData",
    "Lockpick",
    "LockpickData",
    "MagicEffect",
    "MagicEffectData",
    "MiscItem",
    "MiscItemData",
    "Npc",
    "NpcData",
    "NpcStats",
    "PathGrid",
    "PathGridData",
    "PathGridPoint",
    "Probe",
    "ProbeData",
    "Race",
    "RaceData",
    "Reader",
    "Record",
    "Reference",
    "Region",
    "RemoveMasterReport",
    "RenameMasterReport",
    "RepairItem",
    "RepairItemData",
    "Script",
    "ScriptHeader",
    "Skill",
    "SkillData",
    "Sound",
    "SoundData",
    "SoundGen",
    "Spell",
    "SpellData",
    "StartScript",
    "Static",
    "UnknownRecord",
    "Weapon",
    "WeaponData",
    "WeatherChances",
    "Writer",
    "plugin_from_json",
    "plugin_to_json",
    "read_header",
    "read_plugin",
    "record_from_json",
    "record_to_json",
    "remove_master",
    "remove_master_from_bytes",
    "rename_master",
    "rename_master_in_bytes",
    "write_plugin",
]
