"""TES3 plugins as record objects, read and written by greatness7's tes3 crate.

:func:`read_plugin` turns a plugin's bytes into a list of record objects (the
dataclasses in :mod:`wraithguard.esp.records`); :func:`write_plugin` turns them
back. The bytes are the crate's (``tes3::esp``, through ``wraithguard_native``);
the objects are built from, and turned back into, tes3conv-schema JSON by
:mod:`wraithguard.esp.json`. :mod:`wraithguard.esp.enums` and
:mod:`wraithguard.esp.flags` are the crate's enum and bitflags tables. A record type
the crate does not model is kept as an :class:`UnknownRecord` with its raw bytes,
so reading and writing a plugin never loses one.
"""

from __future__ import annotations

from wraithguard.esp.io import EspError
from wraithguard.esp.json import (
    EspJsonError,
    plugin_from_json,
    plugin_to_json,
    record_from_json,
    record_to_json,
)
from wraithguard.esp.masters import (
    RemoveMasterReport,
    RenameMasterReport,
    remove_master,
    remove_master_from_bytes,
    rename_master,
    rename_master_in_bytes,
)
from wraithguard.esp.plugin import read_header, read_plugin, write_plugin
from wraithguard.esp.record import Record, UnknownRecord
from wraithguard.esp.records import (
    Activator,
    Alchemy,
    AlchemyData,
    Apparatus,
    ApparatusData,
    Armor,
    ArmorData,
    AtmosphereData,
    BipedObject,
    Birthsign,
    Bodypart,
    BodypartData,
    Book,
    BookData,
    Cell,
    CellData,
    Class,
    ClassData,
    Clothing,
    ClothingData,
    Container,
    Creature,
    CreatureData,
    Dialogue,
    DialogueData,
    DialogueInfo,
    Door,
    Effect,
    Enchanting,
    EnchantingData,
    Faction,
    FactionData,
    FactionReaction,
    FactionRequirement,
    Filter,
    GameSetting,
    GlobalVariable,
    Header,
    Ingredient,
    IngredientData,
    Landscape,
    LandscapeTexture,
    LeveledCreature,
    LeveledItem,
    Light,
    LightData,
    Lockpick,
    LockpickData,
    MagicEffect,
    MagicEffectData,
    MiscItem,
    MiscItemData,
    Npc,
    NpcData,
    NpcStats,
    PathGrid,
    PathGridData,
    PathGridPoint,
    Probe,
    ProbeData,
    Race,
    RaceData,
    Reference,
    Region,
    RepairItem,
    RepairItemData,
    Script,
    ScriptHeader,
    Skill,
    SkillData,
    Sound,
    SoundData,
    SoundGen,
    Spell,
    SpellData,
    StartScript,
    Static,
    Weapon,
    WeaponData,
    WeatherChances,
)

__all__ = [
    "Activator",
    "Alchemy",
    "AlchemyData",
    "Apparatus",
    "ApparatusData",
    "Armor",
    "ArmorData",
    "AtmosphereData",
    "BipedObject",
    "Birthsign",
    "Bodypart",
    "BodypartData",
    "Book",
    "BookData",
    "Cell",
    "CellData",
    "Class",
    "ClassData",
    "Clothing",
    "ClothingData",
    "Container",
    "Creature",
    "CreatureData",
    "Dialogue",
    "DialogueData",
    "DialogueInfo",
    "Door",
    "Effect",
    "Enchanting",
    "EnchantingData",
    "EspError",
    "EspJsonError",
    "Faction",
    "FactionData",
    "FactionReaction",
    "FactionRequirement",
    "Filter",
    "GameSetting",
    "GlobalVariable",
    "Header",
    "Ingredient",
    "IngredientData",
    "Landscape",
    "LandscapeTexture",
    "LeveledCreature",
    "LeveledItem",
    "Light",
    "LightData",
    "Lockpick",
    "LockpickData",
    "MagicEffect",
    "MagicEffectData",
    "MiscItem",
    "MiscItemData",
    "Npc",
    "NpcData",
    "NpcStats",
    "PathGrid",
    "PathGridData",
    "PathGridPoint",
    "Probe",
    "ProbeData",
    "Race",
    "RaceData",
    "Record",
    "Reference",
    "Region",
    "RemoveMasterReport",
    "RenameMasterReport",
    "RepairItem",
    "RepairItemData",
    "Script",
    "ScriptHeader",
    "Skill",
    "SkillData",
    "Sound",
    "SoundData",
    "SoundGen",
    "Spell",
    "SpellData",
    "StartScript",
    "Static",
    "UnknownRecord",
    "Weapon",
    "WeaponData",
    "WeatherChances",
    "plugin_from_json",
    "plugin_to_json",
    "read_header",
    "read_plugin",
    "record_from_json",
    "record_to_json",
    "remove_master",
    "remove_master_from_bytes",
    "rename_master",
    "rename_master_in_bytes",
    "write_plugin",
]
