//! Morrowind scripts (MWScript): the compiler the editor's Script Edit window saves with.
//!
//! - `compiler`: source to bytecode, a port of MWEdit's compiler, held byte for byte to
//!   MWEdit's own test plugin (`tests/fixtures/mwedit/`, the tests below).
//! - `records`: the load order's records a compile resolves names against, read with the
//!   tes3 crate, plus whatever the editor's patch pool adds.
//! - `check`: the Script Edit window's checks as it is typed (was `mwscript/check.py`).
//! - `data`: MWEdit's grammar and function table, generated by
//!   `tools/gen_mwscript_compiler.py`.
//!
//! `wraithguard/mwscript/compiler.py` is the Python twin: `compile_script` there calls
//! `ScriptCompiler` here when the native module is built, and runs itself when it is not.

pub mod check;
pub mod compiler;
pub mod data;
pub mod records;

use std::path::PathBuf;

use pyo3::prelude::*;
use pyo3::types::{PyBytes, PyDict};

use compiler::{Compiler, CustomFunctions, Levels, default_custom, parse_custom_functions};
use records::{Record, RecordIndex, index_plugins, to_bytes};

/// A record the editor's pool adds or changes: `(tag, id, script, dial_type, shorts,
/// longs, floats)` (`script` empty and `dial_type` -1 when they do not apply).
type Extra = (String, String, String, i32, Vec<String>, Vec<String>, Vec<String>);

/// `ScriptCompiler(plugins, extra=(), custom=None)`: the load order's records, read once,
/// to compile any number of scripts against. `extra` (the patch pool's records) is laid
/// over them; `custom` is a `customfunctions.dat`'s text (the extended MWSE / MW-Enhanced
/// functions), None for the set MWEdit ships.
#[pyclass(frozen, module = "wraithguard_native")]
pub struct ScriptCompiler {
    index: RecordIndex,
    custom: Option<CustomFunctions>,
}

impl ScriptCompiler {
    fn run(&self, source: &[u8], levels: &str, tribunal: bool, bloodmoon: bool, extended: bool) -> compiler::CompileResult {
        let custom: &CustomFunctions = match &self.custom {
            Some(own) => own,
            None => default_custom(),
        };
        Compiler::with_custom(&self.index, Levels::from_name(levels), tribunal, bloodmoon, custom, extended).compile(source)
    }
}

#[pymethods]
impl ScriptCompiler {
    #[new]
    #[pyo3(signature = (plugins, extra=Vec::new(), custom=None))]
    fn new(py: Python<'_>, plugins: Vec<PathBuf>, extra: Vec<Extra>, custom: Option<Vec<u8>>) -> Self {
        let mut index = py.detach(|| index_plugins(&plugins));
        for (tag, id, script, dial_type, shorts, longs, floats) in extra {
            let Ok(rtype) = <[u8; 4]>::try_from(tag.as_bytes()) else { continue };
            let mut rec = Record::new(&rtype, &to_bytes(&id));
            rec.script = to_bytes(&script);
            rec.dial_type = dial_type;
            rec.locals = [shorts, longs, floats].map(|v| v.iter().map(|n| to_bytes(n)).collect());
            index.add(rec);
        }
        let custom = custom.map(|text| parse_custom_functions(&text));
        ScriptCompiler { index, custom }
    }

    /// Distinct IDs indexed.
    fn __len__(&self) -> usize {
        self.index.len()
    }

    /// `script_locals(id)`: the locals of a script, or of the script an object carries
    /// (a dialogue result's speaker), as `(shorts, longs, floats)`; None when it has none.
    fn script_locals<'py>(&self, py: Python<'py>, id: &str) -> Option<[Vec<Bound<'py, PyBytes>>; 3]> {
        let rec = self.index.find(&to_bytes(id))?;
        let script = if &rec.rtype == b"SCPT" { rec } else { self.index.find(&rec.script).filter(|_| !rec.script.is_empty())? };
        if &script.rtype != b"SCPT" {
            return None;
        }
        Some(script.locals.clone().map(|names| names.iter().map(|n| PyBytes::new(py, n)).collect()))
    }

    /// `compile(source, levels="default", tribunal=True, bloodmoon=True, extended=True)`:
    /// the source as the plugin's bytes (Windows-1252). Returns `{ok, name, data,
    /// shorts, longs, floats, var_data, header, messages}`, `messages` as `(line,
    /// column, level, text)`.
    #[pyo3(signature = (source, levels="default", tribunal=true, bloodmoon=true, extended=true))]
    fn compile<'py>(
        &self,
        py: Python<'py>,
        source: &[u8],
        levels: &str,
        tribunal: bool,
        bloodmoon: bool,
        extended: bool,
    ) -> PyResult<Bound<'py, PyDict>> {
        let result = py.detach(|| self.run(source, levels, tribunal, bloodmoon, extended));
        let out = PyDict::new(py);
        let names = |k: usize| -> Vec<Bound<'py, PyBytes>> {
            result.locals[k].iter().map(|n| PyBytes::new(py, n)).collect()
        };
        out.set_item("ok", result.ok)?;
        out.set_item("name", PyBytes::new(py, &result.name))?;
        out.set_item("data", PyBytes::new(py, &result.data))?;
        out.set_item("shorts", names(0))?;
        out.set_item("longs", names(1))?;
        out.set_item("floats", names(2))?;
        out.set_item("var_data", PyBytes::new(py, &result.var_data()))?;
        out.set_item("header", PyBytes::new(py, &result.header()))?;
        let messages: Vec<(usize, usize, &str, String)> =
            result.messages.iter().map(|m| (m.line, m.column, m.level, m.text.clone())).collect();
        out.set_item("messages", messages)?;
        Ok(out)
    }

    /// `compile_record(id, text, levels="default", tribunal=True, bloodmoon=True)`: the
    /// `SCPT` record a save writes, as the tes3 crate's JSON (the editor's record form:
    /// `header`, `variables`, `bytecode` as the patch stores them), or None when the
    /// source does not compile. `text` is kept as given.
    #[pyo3(signature = (id, text, levels="default", tribunal=true, bloodmoon=true, extended=true))]
    #[allow(clippy::too_many_arguments)]
    fn compile_record(
        &self,
        py: Python<'_>,
        id: &str,
        text: &str,
        levels: &str,
        tribunal: bool,
        bloodmoon: bool,
        extended: bool,
    ) -> PyResult<Option<String>> {
        let source = to_bytes(text);
        let result = py.detach(|| self.run(&source, levels, tribunal, bloodmoon, extended));
        if !result.ok {
            return Ok(None);
        }
        let variables = result.var_data();
        let script = tes3::esp::Script {
            id: id.to_string(),
            header: tes3::esp::ScriptHeader {
                num_shorts: result.locals[0].len() as u32,
                num_longs: result.locals[1].len() as u32,
                num_floats: result.locals[2].len() as u32,
                bytecode_length: result.data.len() as u32,
                variables_length: variables.len() as u32,
            },
            variables,
            bytecode: result.data,
            text: text.to_string(),
            ..Default::default()
        };
        let object = tes3::esp::TES3Object::Script(script);
        serde_json::to_string(&object).map(Some).map_err(|e| pyo3::exceptions::PyValueError::new_err(e.to_string()))
    }
}

/// `mwscript_check(text, script_id="", globals=())`: the Script Edit window's checks as
/// it is typed (`check`), `[(line, level, message)]`.
#[pyfunction]
#[pyo3(signature = (text, script_id="", globals=Vec::new()))]
fn mwscript_check(py: Python<'_>, text: &str, script_id: &str, globals: Vec<String>) -> Vec<check::Finding> {
    py.detach(|| check::check_script(text, script_id, &globals))
}

pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<ScriptCompiler>()?;
    m.add_function(wrap_pyfunction!(mwscript_check, m)?)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::compiler::compile;
    use super::*;
    use crate::lint::{records as frames, subrecords};

    const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/fixtures/mwedit/MwEditScriptTest.esp");

    /// Each script's SCHD, SCVR, SCDT and SCTX, straight from the file.
    fn scripts(data: &[u8]) -> Vec<[Vec<u8>; 4]> {
        let mut out = Vec::new();
        for (tag, body) in frames(data) {
            if tag != b"SCPT" {
                continue;
            }
            let mut s: [Vec<u8>; 4] = Default::default();
            for (sub, payload) in subrecords(body) {
                let k = match sub {
                    b"SCHD" => 0,
                    b"SCVR" => 1,
                    b"SCDT" => 2,
                    b"SCTX" => 3,
                    _ => continue,
                };
                s[k] = payload.to_vec();
            }
            out.push(s);
        }
        out
    }

    #[test]
    fn matches_mwedit_byte_for_byte() {
        let data = std::fs::read(FIXTURE).expect("the MWEdit test plugin");
        let index = index_plugins(&[PathBuf::from(FIXTURE)]);
        let all = scripts(&data);
        assert_eq!(all.len(), 34);
        let mut wrong = Vec::new();
        for [schd, scvr, scdt, sctx] in &all {
            let r = compile(sctx, &index, Levels::Default, true, true);
            let name = String::from_utf8_lossy(&schd[..schd.iter().position(|&c| c == 0).unwrap_or(32)]).into_owned();
            if !r.ok || &r.data != scdt || &r.var_data() != scvr || &r.header() != schd {
                let at = r.data.iter().zip(scdt).position(|(a, b)| a != b).unwrap_or(r.data.len().min(scdt.len()));
                wrong.push(format!(
                    "{name}: ok={} got {} bytes, want {}, first difference at {at}; {:?}",
                    r.ok,
                    r.data.len(),
                    scdt.len(),
                    r.messages.iter().map(|m| &m.text).collect::<Vec<_>>()
                ));
            }
        }
        assert!(wrong.is_empty(), "{}", wrong.join("\n"));
    }

    #[test]
    fn return_choice_and_globals() {
        let mut index = RecordIndex::default();
        index.add(Record::new(b"GLOB", b"Gx"));
        let r = compile(b"begin r\nreturn\nend\n", &index, Levels::Default, true, true);
        assert_eq!(r.data, b"\x24\x01\x01\x01");
        let r = compile(b"begin c\nChoice \"Yes\", 1, \"No\", 2\nend\n", &index, Levels::Default, true, true);
        let body: &[u8] = b"\"Yes\" 1 \"No\" 2";
        let mut want = vec![0xC9, 0x10, body.len() as u8, 0];
        want.extend_from_slice(body);
        want.extend_from_slice(b"\x01\x01");
        assert_eq!(r.data, want);
        let r = compile(b"begin g\nset gx to 1\nend\n", &index, Levels::Default, true, true);
        assert_eq!(r.data, b"\x05\x01G\x04Gx\x00\x00\x02 1\x01\x01");
    }

    #[test]
    fn extended_functions_from_mwedit_and_from_a_file() {
        let index = RecordIndex::default();
        let src = b"begin t\nXAddItem \"misc_01\", 10\nend\n";
        let r = compile(src, &index, Levels::Default, true, true);
        assert!(r.ok);
        // Arguments pushed last-first, then the opcode (0x3C28).
        assert_eq!(&r.data[..6], &[0x11u8, 0x38, 10, 0, 0, 0]);
        assert_eq!(&r.data[r.data.len() - 4..r.data.len() - 2], &[0x28u8, 0x3C]);
        let custom = parse_custom_functions(b"# c\nfunction\n Name = XMine # x\n Opcode = 0x3999\n Param1 = Long\nend\n");
        assert_eq!(custom[b"xmine".as_slice()].opcode, 0x3999);
        let r = Compiler::with_custom(&index, Levels::Default, true, true, &custom, true).compile(b"begin t\nXMine 5\nend\n");
        assert!(r.ok);
        assert_eq!(r.data, [0x11u8, 0x38, 5, 0, 0, 0, 0x99, 0x39, 0x01, 0x01]);
    }

    #[test]
    fn unknown_ids_follow_the_message_level() {
        let index = RecordIndex::default();
        let src = b"begin u\nnobody->Disable\nend\n";
        assert!(!compile(src, &index, Levels::Default, true, true).ok);
        let weak = compile(src, &index, Levels::Weak, true, true);
        assert!(weak.ok);
        assert!(weak.messages.iter().any(|m| m.level == "warning"));
    }

    #[test]
    fn a_function_after_choice_is_not_inside_it() {
        let index = RecordIndex::default();
        let src = b"begin u\nChoice \"Yes\" 1 \"No\" 2\nGoodbye\nStopCombat\nend\n";
        let got = compile(src, &index, Levels::Default, true, true);
        assert!(!got.messages.iter().any(|m| m.text.contains("within another function")));
    }
}
